# Generated by Django 3.0.6 on 2020-07-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200716_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes_category',
            name='images',
            field=models.ImageField(default=False, upload_to='%Y/%m/%d'),
        ),
    ]
