# Generated by Django 3.0.6 on 2020-07-16 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clothes_category_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_closet',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Clothes_category'),
        ),
    ]
