# Generated by Django 3.0.6 on 2020-07-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200716_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes_category',
            old_name='images',
            new_name='image',
        ),
    ]
