# Generated by Django 3.0.6 on 2020-07-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200722_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes_category',
            name='bottom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clothes_category',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clothes_category',
            name='outer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clothes_category',
            name='top',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
