# Generated by Django 3.0.6 on 2020-07-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200722_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes_category',
            name='image_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
