# Generated by Django 3.0.6 on 2020-07-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_clothes_category_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes_category',
            name='image_title',
        ),
    ]
