# Generated by Django 3.0.6 on 2020-07-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_clothes_category_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes_category',
            name='image',
            field=models.ImageField(default=False, max_length=255, upload_to='%Y/%m/%d'),
        ),
    ]
