# Generated by Django 3.0.6 on 2020-07-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200723_1814'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='social_login',
            table='social_login',
        ),
    ]
